---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beeteckc/public_html/fylo.beeteck.com.ng
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /usr/local/bin/php $DEPLOYPATH/composer install
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
