---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beeteckc/public_html/fylo.beeteck.com.ng
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /usr/local/bicomposer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan queue:restart
