---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beeteckc/public_html/fylo.beeteck.com.ng
    - /bin/cp -R public/* $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan optimize:clear
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
